[package]
name = "flights"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5"
env_logger = "0.11"
chrono = "0.4.42"
log = "0.4.29"


[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = 0 }
missing_errors_doc = { level = "allow", priority = 1 }
